server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: student-assistant

  datasource:
    url: jdbc:mysql://localhost:3306/student_assistant?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ysnt
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    com.studentassistant: DEBUG
    org.hibernate.SQL: DEBUG